package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONSOMME.
 */
public class Consomme {

    private Long id;
    private Long quantite;
    private Long produit;
    private Long consomme;

    public Consomme() {
    }

    public Consomme(Long id) {
        this.id = id;
    }

    public Consomme(Long id, Long quantite, Long produit, Long consomme) {
        this.id = id;
        this.quantite = quantite;
        this.produit = produit;
        this.consomme = consomme;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getQuantite() {
        return quantite;
    }

    public void setQuantite(Long quantite) {
        this.quantite = quantite;
    }

    public Long getProduit() {
        return produit;
    }

    public void setProduit(Long produit) {
        this.produit = produit;
    }

    public Long getConsomme() {
        return consomme;
    }

    public void setConsomme(Long consomme) {
        this.consomme = consomme;
    }

}
