package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Produit;

import greendao.ProduitDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig produitDaoConfig;

    private final ProduitDao produitDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        produitDaoConfig = daoConfigMap.get(ProduitDao.class).clone();
        produitDaoConfig.initIdentityScope(type);

        produitDao = new ProduitDao(produitDaoConfig, this);

        registerDao(Produit.class, produitDao);
    }
    
    public void clear() {
        produitDaoConfig.getIdentityScope().clear();
    }

    public ProduitDao getProduitDao() {
        return produitDao;
    }

}
