package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Categorie;
import greendao.Produit;
import greendao.Commande;
import greendao.Consomme;

import greendao.CategorieDao;
import greendao.ProduitDao;
import greendao.CommandeDao;
import greendao.ConsommeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categorieDaoConfig;
    private final DaoConfig produitDaoConfig;
    private final DaoConfig commandeDaoConfig;
    private final DaoConfig consommeDaoConfig;

    private final CategorieDao categorieDao;
    private final ProduitDao produitDao;
    private final CommandeDao commandeDao;
    private final ConsommeDao consommeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categorieDaoConfig = daoConfigMap.get(CategorieDao.class).clone();
        categorieDaoConfig.initIdentityScope(type);

        produitDaoConfig = daoConfigMap.get(ProduitDao.class).clone();
        produitDaoConfig.initIdentityScope(type);

        commandeDaoConfig = daoConfigMap.get(CommandeDao.class).clone();
        commandeDaoConfig.initIdentityScope(type);

        consommeDaoConfig = daoConfigMap.get(ConsommeDao.class).clone();
        consommeDaoConfig.initIdentityScope(type);

        categorieDao = new CategorieDao(categorieDaoConfig, this);
        produitDao = new ProduitDao(produitDaoConfig, this);
        commandeDao = new CommandeDao(commandeDaoConfig, this);
        consommeDao = new ConsommeDao(consommeDaoConfig, this);

        registerDao(Categorie.class, categorieDao);
        registerDao(Produit.class, produitDao);
        registerDao(Commande.class, commandeDao);
        registerDao(Consomme.class, consommeDao);
    }
    
    public void clear() {
        categorieDaoConfig.getIdentityScope().clear();
        produitDaoConfig.getIdentityScope().clear();
        commandeDaoConfig.getIdentityScope().clear();
        consommeDaoConfig.getIdentityScope().clear();
    }

    public CategorieDao getCategorieDao() {
        return categorieDao;
    }

    public ProduitDao getProduitDao() {
        return produitDao;
    }

    public CommandeDao getCommandeDao() {
        return commandeDao;
    }

    public ConsommeDao getConsommeDao() {
        return consommeDao;
    }

}
