package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Categorie;

import greendao.CategorieDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categorieDaoConfig;

    private final CategorieDao categorieDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categorieDaoConfig = daoConfigMap.get(CategorieDao.class).clone();
        categorieDaoConfig.initIdentityScope(type);

        categorieDao = new CategorieDao(categorieDaoConfig, this);

        registerDao(Categorie.class, categorieDao);
    }
    
    public void clear() {
        categorieDaoConfig.getIdentityScope().clear();
    }

    public CategorieDao getCategorieDao() {
        return categorieDao;
    }

}
